name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches:
      - main # Production branch
      - staging # Staging branch
      - dev # Development branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - staging
      - dev

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read
      pull-requests: write
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set environment variables
        id: set-env-vars
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "APP_LOCATION=/"
            echo "API_LOCATION=api"
            echo "APP_ARTIFACT_LOCATION=build"
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}"
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "APP_LOCATION=/"
            echo "API_LOCATION=staging-api"
            echo "APP_ARTIFACT_LOCATION=staging-build"
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}"
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "APP_LOCATION=/"
            echo "API_LOCATION=dev-api"
            echo "APP_ARTIFACT_LOCATION=dev-build"
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}"
          fi
        shell: bash

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.set-env-vars.outputs.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ steps.set-env-vars.outputs.APP_LOCATION }}
          api_location: ${{ steps.set-env-vars.outputs.API_LOCATION }}
          app_artifact_location: ${{ steps.set-env-vars.outputs.APP_ARTIFACT_LOCATION }}

  close_pull_request_job:
    permissions:
      contents: none
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # Adjust this for the environment
          action: "close"
